/**
 * @fileoverview AI-Powered PR Description Generator Models
 *
 * Types for automated PR description generation from commits,
 * diffs, and linked issues. Includes template customization
 * and quality assessment.
 *
 * @module models/pr-description-generator
 */

// ============================================
// Description Generation Types
// ============================================

/**
 * PR description generation request
 */
export interface DescriptionGenerationRequest {
  /** Repository */
  repository: { owner: string; name: string };
  /** PR number (if updating existing) */
  prNumber?: number;
  /** Branch name */
  branch: string;
  /** Base branch */
  baseBranch: string;
  /** Commit messages */
  commits: PRCommit[];
  /** Diff summary */
  diffSummary: {
    filesChanged: number;
    additions: number;
    deletions: number;
    fileTypes: Record<string, number>;
  };
  /** Linked issues/tickets */
  linkedIssues?: LinkedIssue[];
  /** Template to use */
  templateId?: string;
  /** Preferred length */
  preferredLength?: 'concise' | 'standard' | 'detailed';
}

/**
 * A commit in the PR
 */
export interface PRCommit {
  /** Commit SHA */
  sha: string;
  /** Commit message */
  message: string;
  /** Author */
  author: string;
  /** Files changed */
  filesChanged: string[];
  /** Timestamp */
  timestamp: Date;
}

/**
 * A linked issue or ticket
 */
export interface LinkedIssue {
  /** Issue type */
  type: 'github_issue' | 'jira' | 'linear' | 'other';
  /** Issue key/number */
  key: string;
  /** Issue title */
  title: string;
  /** Issue body (if available) */
  body?: string;
  /** Issue URL */
  url?: string;
}

/**
 * Generated PR description
 */
export interface GeneratedDescription {
  /** Generation ID */
  id: string;
  /** Generated title */
  title: string;
  /** Generated body (markdown) */
  body: string;
  /** Sections included */
  sections: DescriptionSection[];
  /** Suggested labels */
  suggestedLabels: string[];
  /** Suggested reviewers */
  suggestedReviewers: string[];
  /** Quality score */
  quality: DescriptionQuality;
  /** Template used */
  templateId?: string;
  /** Generated at */
  generatedAt: Date;
}

/**
 * A section of the description
 */
export interface DescriptionSection {
  /** Section key */
  key: string;
  /** Section heading */
  heading: string;
  /** Section content */
  content: string;
  /** Whether this section was auto-generated */
  autoGenerated: boolean;
  /** Source of the content */
  source: 'commits' | 'diff' | 'issues' | 'template' | 'ai_generated';
}

/**
 * Description quality assessment
 */
export interface DescriptionQuality {
  /** Overall score (0-100) */
  overall: number;
  /** Completeness (0-100) */
  completeness: number;
  /** Clarity (0-100) */
  clarity: number;
  /** Accuracy (0-100) */
  accuracy: number;
  /** Missing sections */
  missingSections: string[];
  /** Improvement suggestions */
  suggestions: string[];
}

// ============================================
// Template Types
// ============================================

/**
 * PR description template
 */
export interface DescriptionTemplate {
  /** Template ID */
  id: string;
  /** Template name */
  name: string;
  /** Description */
  description: string;
  /** Template content (with placeholders) */
  content: string;
  /** Required sections */
  requiredSections: string[];
  /** Optional sections */
  optionalSections: string[];
  /** Scope */
  scope: 'repository' | 'organization' | 'global';
  /** Usage count */
  usageCount: number;
  /** Created by */
  createdBy: string;
  /** Created at */
  createdAt: Date;
}
