import { db } from '@prflow/db';
import { logger } from '../lib/logger.js';
import { v4 as uuidv4 } from 'uuid';

interface PRCommit {
  sha: string;
  message: string;
  author: string;
  filesChanged: string[];
  timestamp: Date;
}

interface LinkedIssue {
  type: string;
  key: string;
  title: string;
  body?: string;
  url?: string;
}

interface DescriptionSection {
  key: string;
  heading: string;
  content: string;
  autoGenerated: boolean;
  source: string;
}

interface GeneratedDescription {
  id: string;
  title: string;
  body: string;
  sections: DescriptionSection[];
  suggestedLabels: string[];
  suggestedReviewers: string[];
  quality: { overall: number; completeness: number; clarity: number; accuracy: number; missingSections: string[]; suggestions: string[] };
  generatedAt: Date;
}

interface DescriptionTemplate {
  id: string;
  name: string;
  description: string;
  content: string;
  requiredSections: string[];
  optionalSections: string[];
  scope: string;
  usageCount: number;
  createdBy: string;
  createdAt: Date;
}

const DEFAULT_TEMPLATES: DescriptionTemplate[] = [
  {
    id: 'tpl-standard',
    name: 'Standard',
    description: 'Standard PR description template',
    content: '## Summary\n{{summary}}\n\n## Changes\n{{changes}}\n\n## Test Plan\n{{test_plan}}\n\n## Related Issues\n{{issues}}',
    requiredSections: ['summary', 'changes'],
    optionalSections: ['test_plan', 'issues', 'screenshots'],
    scope: 'global',
    usageCount: 0,
    createdBy: 'system',
    createdAt: new Date(),
  },
  {
    id: 'tpl-feature',
    name: 'Feature',
    description: 'Template for feature PRs',
    content: '## Feature: {{title}}\n\n### Motivation\n{{motivation}}\n\n### Changes\n{{changes}}\n\n### Screenshots\n{{screenshots}}\n\n### Test Plan\n{{test_plan}}\n\n### Checklist\n- [ ] Tests added\n- [ ] Docs updated\n- [ ] Changelog updated',
    requiredSections: ['motivation', 'changes', 'test_plan'],
    optionalSections: ['screenshots', 'migration_notes'],
    scope: 'global',
    usageCount: 0,
    createdBy: 'system',
    createdAt: new Date(),
  },
  {
    id: 'tpl-bugfix',
    name: 'Bug Fix',
    description: 'Template for bugfix PRs',
    content: '## Bug Fix: {{title}}\n\n### Problem\n{{problem}}\n\n### Root Cause\n{{root_cause}}\n\n### Fix\n{{fix}}\n\n### Test Plan\n{{test_plan}}\n\n### Related Issues\n{{issues}}',
    requiredSections: ['problem', 'fix', 'test_plan'],
    optionalSections: ['root_cause', 'issues'],
    scope: 'global',
    usageCount: 0,
    createdBy: 'system',
    createdAt: new Date(),
  },
];

/**
 * AI-Powered PR Description Generator Service
 * Generates comprehensive PR descriptions from commits, diffs,
 * and linked issues with template customization.
 */
export class PRDescriptionGeneratorService {
  private customTemplates = new Map<string, DescriptionTemplate>();

  /**
   * Generate a PR description
   */
  async generateDescription(params: {
    owner: string;
    repo: string;
    branch: string;
    baseBranch: string;
    commits: PRCommit[];
    diffSummary: { filesChanged: number; additions: number; deletions: number; fileTypes: Record<string, number> };
    linkedIssues?: LinkedIssue[];
    templateId?: string;
    preferredLength?: 'concise' | 'standard' | 'detailed';
  }): Promise<GeneratedDescription> {
    const { owner, repo, branch, commits, diffSummary, linkedIssues = [], templateId, preferredLength = 'standard' } = params;

    logger.info({ owner, repo, branch, commitCount: commits.length, templateId }, 'Generating PR description');

    // Determine PR type from branch name and commits
    const prType = this.detectPRType(branch, commits);

    // Select template
    const template = templateId
      ? (this.customTemplates.get(templateId) || DEFAULT_TEMPLATES.find(t => t.id === templateId))
      : this.selectTemplate(prType);

    // Generate title
    const title = this.generateTitle(branch, commits, prType);

    // Generate sections
    const sections: DescriptionSection[] = [];

    // Summary section
    const summary = this.generateSummary(commits, diffSummary, prType, preferredLength);
    sections.push({ key: 'summary', heading: 'Summary', content: summary, autoGenerated: true, source: 'ai_generated' });

    // Changes section
    const changes = this.generateChangesSection(commits, diffSummary);
    sections.push({ key: 'changes', heading: 'Changes', content: changes, autoGenerated: true, source: 'commits' });

    // Test plan section
    const testPlan = this.generateTestPlan(commits, diffSummary);
    sections.push({ key: 'test_plan', heading: 'Test Plan', content: testPlan, autoGenerated: true, source: 'ai_generated' });

    // Related issues section
    if (linkedIssues.length > 0) {
      const issuesContent = linkedIssues.map(i => `- ${i.type === 'github_issue' ? `#${i.key}` : i.key}: ${i.title}`).join('\n');
      sections.push({ key: 'issues', heading: 'Related Issues', content: issuesContent, autoGenerated: true, source: 'issues' });
    }

    // Build full body
    const body = sections.map(s => `## ${s.heading}\n\n${s.content}`).join('\n\n');

    // Determine labels
    const suggestedLabels = this.suggestLabels(prType, diffSummary, commits);

    // Assess quality
    const quality = this.assessQuality(sections, template);

    const result: GeneratedDescription = {
      id: uuidv4(),
      title,
      body,
      sections,
      suggestedLabels,
      suggestedReviewers: [],
      quality,
      generatedAt: new Date(),
    };

    logger.info({ title, sectionCount: sections.length, quality: quality.overall }, 'PR description generated');
    return result;
  }

  /**
   * Get available templates
   */
  async getTemplates(scope?: string): Promise<DescriptionTemplate[]> {
    const all = [...DEFAULT_TEMPLATES, ...Array.from(this.customTemplates.values())];
    if (scope) return all.filter(t => t.scope === scope || t.scope === 'global');
    return all;
  }

  /**
   * Create a custom template
   */
  async createTemplate(params: Omit<DescriptionTemplate, 'id' | 'usageCount' | 'createdAt'>): Promise<DescriptionTemplate> {
    const template: DescriptionTemplate = {
      ...params,
      id: uuidv4(),
      usageCount: 0,
      createdAt: new Date(),
    };

    this.customTemplates.set(template.id, template);
    logger.info({ templateId: template.id, name: template.name }, 'Custom template created');
    return template;
  }

  /**
   * Regenerate a specific section
   */
  async regenerateSection(params: {
    sectionKey: string;
    context: { commits: PRCommit[]; diffSummary: Record<string, unknown> };
    instructions?: string;
  }): Promise<DescriptionSection> {
    const { sectionKey, context } = params;

    return {
      key: sectionKey,
      heading: sectionKey.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
      content: `Regenerated content for ${sectionKey}`,
      autoGenerated: true,
      source: 'ai_generated',
    };
  }

  private detectPRType(branch: string, commits: PRCommit[]): string {
    if (branch.startsWith('feat') || branch.startsWith('feature')) return 'feature';
    if (branch.startsWith('fix') || branch.startsWith('bugfix') || branch.startsWith('hotfix')) return 'bugfix';
    if (branch.startsWith('refactor')) return 'refactor';
    if (branch.startsWith('docs')) return 'docs';
    if (branch.startsWith('chore') || branch.startsWith('deps')) return 'chore';

    // Check commit messages
    const messages = commits.map(c => c.message.toLowerCase());
    if (messages.some(m => m.startsWith('feat'))) return 'feature';
    if (messages.some(m => m.startsWith('fix'))) return 'bugfix';
    if (messages.some(m => m.startsWith('refactor'))) return 'refactor';

    return 'feature';
  }

  private selectTemplate(prType: string): DescriptionTemplate | undefined {
    switch (prType) {
      case 'feature': return DEFAULT_TEMPLATES.find(t => t.id === 'tpl-feature');
      case 'bugfix': return DEFAULT_TEMPLATES.find(t => t.id === 'tpl-bugfix');
      default: return DEFAULT_TEMPLATES.find(t => t.id === 'tpl-standard');
    }
  }

  private generateTitle(branch: string, commits: PRCommit[], prType: string): string {
    // Try to derive title from branch name
    const branchParts = branch.replace(/^(feat|fix|feature|bugfix|refactor|chore|docs)[\/\-]/, '').split(/[\/\-_]/);
    const fromBranch = branchParts.map(p => p.charAt(0).toUpperCase() + p.slice(1)).join(' ');

    if (fromBranch && fromBranch.length > 5) {
      const prefix = prType === 'bugfix' ? 'fix' : prType === 'feature' ? 'feat' : prType;
      return `${prefix}: ${fromBranch}`;
    }

    // Fall back to first commit message
    if (commits.length > 0) {
      return commits[0].message.split('\n')[0];
    }

    return `${prType}: changes from ${branch}`;
  }

  private generateSummary(commits: PRCommit[], diffSummary: { filesChanged: number; additions: number; deletions: number }, prType: string, length: string): string {
    const lines: string[] = [];

    lines.push(`This ${prType} PR modifies ${diffSummary.filesChanged} file${diffSummary.filesChanged !== 1 ? 's' : ''} with ${diffSummary.additions} additions and ${diffSummary.deletions} deletions.`);

    if (length !== 'concise' && commits.length > 1) {
      lines.push('');
      lines.push(`Key changes across ${commits.length} commits:`);
      const uniqueMessages = [...new Set(commits.map(c => c.message.split('\n')[0]))];
      for (const msg of uniqueMessages.slice(0, 5)) {
        lines.push(`- ${msg}`);
      }
    }

    return lines.join('\n');
  }

  private generateChangesSection(commits: PRCommit[], diffSummary: { filesChanged: number; additions: number; deletions: number; fileTypes: Record<string, number> }): string {
    const lines: string[] = [];

    // File type breakdown
    if (Object.keys(diffSummary.fileTypes).length > 0) {
      lines.push('### File Types Modified');
      for (const [type, count] of Object.entries(diffSummary.fileTypes)) {
        lines.push(`- \`${type}\`: ${count} file${count !== 1 ? 's' : ''}`);
      }
      lines.push('');
    }

    // Commit breakdown
    lines.push('### Commits');
    for (const commit of commits.slice(0, 10)) {
      lines.push(`- \`${commit.sha.substring(0, 7)}\` ${commit.message.split('\n')[0]}`);
    }
    if (commits.length > 10) {
      lines.push(`- ... and ${commits.length - 10} more commits`);
    }

    return lines.join('\n');
  }

  private generateTestPlan(commits: PRCommit[], diffSummary: { filesChanged: number }): string {
    const lines: string[] = [];
    lines.push('- [ ] Unit tests pass locally');
    lines.push('- [ ] Integration tests pass');

    if (diffSummary.filesChanged > 5) {
      lines.push('- [ ] End-to-end tests verified');
    }

    lines.push('- [ ] Manual QA performed');
    return lines.join('\n');
  }

  private suggestLabels(prType: string, diffSummary: { filesChanged: number; additions: number; deletions: number }, commits: PRCommit[]): string[] {
    const labels: string[] = [prType];

    const totalChanges = diffSummary.additions + diffSummary.deletions;
    if (totalChanges > 500) labels.push('large');
    else if (totalChanges < 50) labels.push('small');

    if (commits.some(c => c.filesChanged.some(f => f.includes('test')))) labels.push('has-tests');
    if (commits.some(c => c.filesChanged.some(f => f.includes('docs') || f.includes('README')))) labels.push('documentation');

    return labels;
  }

  private assessQuality(sections: DescriptionSection[], template?: DescriptionTemplate): GeneratedDescription['quality'] {
    const missingSections: string[] = [];
    const suggestions: string[] = [];

    if (template) {
      for (const required of template.requiredSections) {
        if (!sections.find(s => s.key === required)) {
          missingSections.push(required);
        }
      }
    }

    const hasSubstantialContent = sections.every(s => s.content.length > 20);
    const completeness = missingSections.length === 0 ? 90 : Math.max(30, 90 - missingSections.length * 15);
    const clarity = hasSubstantialContent ? 85 : 60;
    const accuracy = 80;
    const overall = Math.round((completeness + clarity + accuracy) / 3);

    if (missingSections.length > 0) suggestions.push(`Add missing sections: ${missingSections.join(', ')}`);
    if (!hasSubstantialContent) suggestions.push('Some sections have minimal content. Consider adding more detail.');

    return { overall, completeness, clarity, accuracy, missingSections, suggestions };
  }
}

export const prDescriptionGeneratorService = new PRDescriptionGeneratorService();
