import type { FastifyInstance } from 'fastify';
import { healthRoutes } from './health.js';
import { repositoryRoutes } from './repositories.js';
import { workflowRoutes } from './workflows.js';
import { analyticsRoutes } from './analytics.js';
import { rulesRoutes } from './rules.js';
import { auditRoutes } from './audit.js';
import { authRoutes } from './auth.js';
import { mergeQueueRoutes } from './merge-queue.js';
import { teamAnalyticsRoutes } from './team-analytics.js';
import { enterpriseRoutes } from './enterprise.js';
import { registerBatchRoutes } from './batch.js';
import { registerOpenAPI } from './openapi.js';
import { reviewerRoutes } from './reviewers.js';
import { fixRoutes } from './fixes.js';
import { healthScoreRoutes } from './health-score.js';
import { learningRoutes } from './learning.js';
import { prSplittingRoutes } from './pr-splitting.js';
import { collaborativeReviewRoutes } from './collaborative-review.js';
import { securityRoutes } from './security.js';
import conflictResolutionRoutes from './conflict-resolution.js';
import reviewPersonasRoutes from './review-personas.js';
import testPrioritizationRoutes from './test-prioritization.js';
import multiRepoOrchestrationRoutes from './multi-repo-orchestration.js';
import { pairReviewRoutes } from './pair-review.js';
import { predictiveHealthRoutes } from './predictive-health.js';
import { knowledgeGraphRoutes } from './knowledge-graph.js';
import { autoRemediationRoutes } from './auto-remediation.js';
import { reviewReplayRoutes } from './review-replay.js';
import { prDecompositionRoutes } from './pr-decomposition.js';
import { securityComplianceRoutes } from './security-compliance.js';
import { idePreFlightRoutes } from './ide-preflight.js';
import { teamVelocityRoutes } from './team-velocity.js';
import { enhancedMultiRepoRoutes } from './enhanced-multi-repo.js';
import { prDependencyGraphRoutes } from './pr-dependency-graph.js';
import { naturalLanguageQueryRoutes } from './natural-language-query.js';
import { mlTrainingRoutes } from './ml-training.js';
import { interactiveTrainingRoutes } from './interactive-training.js';
import { migrationRoutes } from './migration.js';
import { intentRoutes } from './intent.js';
import { debtDashboardRoutes } from './debt-dashboard.js';
import { semverRoutes } from './semver.js';
import { timeMachineRoutes } from './time-machine.js';
import { impactSimulatorRoutes } from './impact-simulator.js';
import { marketplaceRoutes } from './marketplace.js';
import { conflictPreventionRoutes } from './conflict-prevention.js';
import { runbookRoutes } from './runbook.js';
import { voiceReviewRoutes } from './voice-review.js';

export async function setupRoutes(app: FastifyInstance) {
  await app.register(healthRoutes, { prefix: '/api' });
  await app.register(authRoutes, { prefix: '/api/auth' });
  await app.register(repositoryRoutes, { prefix: '/api/repositories' });
  await app.register(workflowRoutes, { prefix: '/api/workflows' });
  await app.register(analyticsRoutes, { prefix: '/api/analytics' });
  await app.register(teamAnalyticsRoutes, { prefix: '/api/teams' });
  await app.register(rulesRoutes, { prefix: '/api/rules' });
  await app.register(auditRoutes, { prefix: '/api/audit' });
  await app.register(mergeQueueRoutes, { prefix: '/api' });
  await app.register(enterpriseRoutes, { prefix: '/api/enterprise' });
  await app.register(reviewerRoutes, { prefix: '/api' });
  await app.register(fixRoutes, { prefix: '/api/fixes' });
  await app.register(healthScoreRoutes, { prefix: '/api/health' });
  await app.register(learningRoutes, { prefix: '/api/learning' });
  await app.register(prSplittingRoutes, { prefix: '/api/splitting' });
  await app.register(collaborativeReviewRoutes, { prefix: '/api/collab' });
  await app.register(securityRoutes, { prefix: '/api/security' });
  await app.register(conflictResolutionRoutes);
  await app.register(reviewPersonasRoutes);
  await app.register(testPrioritizationRoutes);
  await app.register(multiRepoOrchestrationRoutes);
  await app.register(pairReviewRoutes, { prefix: '/api/pair-review' });
  await app.register(predictiveHealthRoutes, { prefix: '/api/predictions' });
  await app.register(knowledgeGraphRoutes, { prefix: '/api/graph' });
  await app.register(autoRemediationRoutes, { prefix: '/api' });
  await app.register(reviewReplayRoutes, { prefix: '/api' });
  await app.register(prDecompositionRoutes, { prefix: '/api' });
  await app.register(securityComplianceRoutes, { prefix: '/api' });
  await app.register(idePreFlightRoutes, { prefix: '/api' });
  await app.register(teamVelocityRoutes, { prefix: '/api' });
  await app.register(enhancedMultiRepoRoutes, { prefix: '/api' });
  await app.register(prDependencyGraphRoutes, { prefix: '/api' });
  await app.register(naturalLanguageQueryRoutes, { prefix: '/api' });
  await app.register(mlTrainingRoutes, { prefix: '/api/ml' });
  await app.register(interactiveTrainingRoutes, { prefix: '/api' });
  await app.register(migrationRoutes, { prefix: '/api' });
  await app.register(intentRoutes, { prefix: '/api' });
  await app.register(debtDashboardRoutes, { prefix: '/api' });
  await app.register(semverRoutes, { prefix: '/api/semver' });
  await app.register(timeMachineRoutes, { prefix: '/api/time-machine' });
  await app.register(impactSimulatorRoutes, { prefix: '/api/impact' });
  await app.register(marketplaceRoutes, { prefix: '/api/marketplace' });
  await app.register(conflictPreventionRoutes, { prefix: '/api/conflicts' });
  await app.register(runbookRoutes, { prefix: '/api/runbooks' });
  await app.register(voiceReviewRoutes, { prefix: '/api/voice' });
  registerBatchRoutes(app);
  registerOpenAPI(app);
}
